import { format, parseISO } from "date-fns";

export const generateExpensesPDF = (expenses, clients) => {
  const getClientName = (clientId) => {
    const client = clients?.find(c => c.id === clientId);
    return client?.name || "Unknown";
  };

  const totalIncome = expenses.filter(e => e.type === "income").reduce((sum, e) => sum + (e.amount || 0), 0);
  const totalOutcome = expenses.filter(e => e.type === "outcome").reduce((sum, e) => sum + (e.amount || 0), 0);
  const netBalance = totalIncome - totalOutcome;

  let html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Expenses Report</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 3px solid #10b981; padding-bottom: 20px; }
        .header h1 { margin: 0; color: #10b981; }
        .header p { color: #666; margin: 5px 0; }
        .summary { display: flex; justify-content: space-around; margin: 30px 0; padding: 20px; background: #f8f9fa; border-radius: 8px; }
        .summary-item { text-align: center; }
        .summary-item h3 { margin: 0; font-size: 14px; color: #666; text-transform: uppercase; }
        .summary-item p { margin: 5px 0 0; font-size: 24px; font-weight: bold; }
        .income { color: #10b981; }
        .outcome { color: #ef4444; }
        .balance { color: #3b82f6; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #f1f5f9; padding: 12px; text-align: left; font-weight: 600; border-bottom: 2px solid #e2e8f0; }
        td { padding: 12px; border-bottom: 1px solid #e2e8f0; }
        tr:hover { background: #f8fafc; }
        .badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 11px; font-weight: 600; }
        .badge-income { background: #d1fae5; color: #065f46; }
        .badge-outcome { background: #fee2e2; color: #991b1b; }
        .badge-personal { background: #dbeafe; color: #1e40af; }
        .badge-client { background: #e9d5ff; color: #6b21a8; }
        .footer { margin-top: 40px; text-align: center; color: #999; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Expenses Report</h1>
        <p>Generated on ${format(new Date(), "MMMM d, yyyy 'at' h:mm a")}</p>
        <p>Total Records: ${expenses.length}</p>
      </div>

      <div class="summary">
        <div class="summary-item">
          <h3>Total Income</h3>
          <p class="income">$${totalIncome.toLocaleString(undefined, { minimumFractionDigits: 2 })}</p>
        </div>
        <div class="summary-item">
          <h3>Total Outcome</h3>
          <p class="outcome">$${totalOutcome.toLocaleString(undefined, { minimumFractionDigits: 2 })}</p>
        </div>
        <div class="summary-item">
          <h3>Net Balance</h3>
          <p class="balance">$${netBalance.toLocaleString(undefined, { minimumFractionDigits: 2 })}</p>
        </div>
      </div>

      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Title</th>
            <th>Type</th>
            <th>Amount</th>
            <th>Client</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
  `;

  expenses.forEach(expense => {
    const typeBadge = expense.type === "income" 
      ? '<span class="badge badge-income">Income</span>' 
      : '<span class="badge badge-outcome">Outcome</span>';
    
    const clientInfo = expense.is_personal === false && expense.client_id
      ? `<span class="badge badge-client">${getClientName(expense.client_id)}</span>`
      : '<span class="badge badge-personal">Personal</span>';

    html += `
      <tr>
        <td>${format(parseISO(expense.date), "MMM d, yyyy")}</td>
        <td>${expense.title || ""}</td>
        <td>${typeBadge}</td>
        <td style="font-weight: 600;">${expense.currency || "$"}${(expense.amount || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
        <td>${clientInfo}</td>
        <td style="font-size: 12px; color: #666;">${expense.notes || "-"}</td>
      </tr>
    `;
  });

  html += `
        </tbody>
      </table>
      <div class="footer">
        <p>This report was automatically generated by Tracker App</p>
      </div>
    </body>
    </html>
  `;

  return html;
};

export const generateEventsPDF = (events, clients) => {
  const getClientName = (clientId) => {
    const client = clients?.find(c => c.id === clientId);
    return client?.name || "Unknown";
  };

  const upcomingCount = events.filter(e => e.status === "upcoming").length;
  const completedCount = events.filter(e => e.status === "completed").length;
  const cancelledCount = events.filter(e => e.status === "cancelled").length;

  let html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Events Report</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 3px solid #10b981; padding-bottom: 20px; }
        .header h1 { margin: 0; color: #10b981; }
        .header p { color: #666; margin: 5px 0; }
        .summary { display: flex; justify-content: space-around; margin: 30px 0; padding: 20px; background: #f8f9fa; border-radius: 8px; }
        .summary-item { text-align: center; }
        .summary-item h3 { margin: 0; font-size: 14px; color: #666; text-transform: uppercase; }
        .summary-item p { margin: 5px 0 0; font-size: 24px; font-weight: bold; }
        .upcoming { color: #10b981; }
        .completed { color: #64748b; }
        .cancelled { color: #ef4444; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #f1f5f9; padding: 12px; text-align: left; font-weight: 600; border-bottom: 2px solid #e2e8f0; }
        td { padding: 12px; border-bottom: 1px solid #e2e8f0; }
        tr:hover { background: #f8fafc; }
        .badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 11px; font-weight: 600; }
        .badge-upcoming { background: #d1fae5; color: #065f46; }
        .badge-completed { background: #f1f5f9; color: #334155; }
        .badge-cancelled { background: #fee2e2; color: #991b1b; }
        .badge-personal { background: #dbeafe; color: #1e40af; }
        .badge-client { background: #e9d5ff; color: #6b21a8; }
        .footer { margin-top: 40px; text-align: center; color: #999; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Events Report</h1>
        <p>Generated on ${format(new Date(), "MMMM d, yyyy 'at' h:mm a")}</p>
        <p>Total Events: ${events.length}</p>
      </div>

      <div class="summary">
        <div class="summary-item">
          <h3>Upcoming</h3>
          <p class="upcoming">${upcomingCount}</p>
        </div>
        <div class="summary-item">
          <h3>Completed</h3>
          <p class="completed">${completedCount}</p>
        </div>
        <div class="summary-item">
          <h3>Cancelled</h3>
          <p class="cancelled">${cancelledCount}</p>
        </div>
      </div>

      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Title</th>
            <th>Status</th>
            <th>Location</th>
            <th>Client</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
  `;

  events.forEach(event => {
    const statusBadge = event.status === "upcoming" 
      ? '<span class="badge badge-upcoming">Upcoming</span>'
      : event.status === "completed"
      ? '<span class="badge badge-completed">Completed</span>'
      : '<span class="badge badge-cancelled">Cancelled</span>';
    
    const clientInfo = event.is_personal === false && event.client_id
      ? `<span class="badge badge-client">${getClientName(event.client_id)}</span>`
      : '<span class="badge badge-personal">Personal</span>';

    html += `
      <tr>
        <td>${format(parseISO(event.date), "MMM d, yyyy")}</td>
        <td>${event.time || "-"}</td>
        <td style="font-weight: 600;">${event.title || ""}</td>
        <td>${statusBadge}</td>
        <td>${event.location || "-"}</td>
        <td>${clientInfo}</td>
        <td style="font-size: 12px; color: #666;">${event.description || "-"}</td>
      </tr>
    `;
  });

  html += `
        </tbody>
      </table>
      <div class="footer">
        <p>This report was automatically generated by Tracker App</p>
      </div>
    </body>
    </html>
  `;

  return html;
};
