import { supabase } from "../../../../lib/supabase-client.js";
import { normalizeTaxPercent } from "@/lib/taxRate";
import { sendRawEmail, tenantEmailFromName } from "@/lib/orderEmails";

export const num = (v) => {
  const n = typeof v === "number" ? v : parseFloat(v);
  return Number.isFinite(n) ? n : 0;
};

export const TERMS = {
  due_on_receipt: { days: 0, es: "Pago al recibir", en: "Due on receipt" },
  net_15: { days: 15, es: "Net 15", en: "Net 15" },
  net_30: { days: 30, es: "Net 30", en: "Net 30" },
  net_60: { days: 60, es: "Net 60", en: "Net 60" },
};

export const termsLabel = (key, lang) => (TERMS[key] || TERMS.due_on_receipt)[lang === "en" ? "en" : "es"];
export function dueDateFor(key, issued) {
  const d = (TERMS[key] || TERMS.due_on_receipt).days;
  if (d <= 0) return null;
  const r = new Date(issued);
  r.setDate(r.getDate() + d);
  return r;
}

const S = {
  invoice: ["FACTURA", "INVOICE"], billTo: ["FACTURAR A", "BILL TO"], issued: ["Emitida", "Issued"], due: ["Vence", "Due"],
  period: ["PERÍODO FACTURADO", "BILLING PERIOD"], colOrder: ["ORDEN", "ORDER"], colService: ["SERVICIO", "SERVICE"],
  colDates: ["RECIBIDO / ENTREGADO", "RECEIVED / DELIVERED"], colAmount: ["MONTO", "AMOUNT"], subtotal: ["Subtotal", "Subtotal"], total: ["TOTAL", "TOTAL"],
  notes: ["NOTAS", "NOTES"], contact: ["Contacto", "Contact"], phone: ["Tel", "Phone"], merchantReg: ["Reg. Comerciante", "Merchant Reg."],
  customerTaxId: ["Reg. / EIN", "Tax ID / EIN"], terms: ["Términos de pago", "Payment terms"], thanks: ["Gracias por su preferencia", "Thank you for your business"],
  generatedBy: ["Generado por Archilla OS", "Generated by Archilla OS"], workshopFallback: ["Taller de Reparación", "Repair Shop"], voided: ["ANULADA", "VOIDED"],
};
export const str = (key, lang) => S[key][lang === "en" ? 1 : 0];

export function devicesLabel(n, lang) {
  if (lang === "en") return n === 1 ? "1 device" : `${n} devices`;
  return n === 1 ? "1 equipo" : `${n} equipos`;
}

const locale = (lang) => (lang === "en" ? "en-US" : "es-PR");
export const fmtDate = (d, lang) => new Intl.DateTimeFormat(locale(lang), { day: "numeric", month: "short", year: "numeric" }).format(d).replace(/\./g, "");
export const fmtShort = (d, lang) => new Intl.DateTimeFormat(locale(lang), { day: "numeric", month: "short" }).format(d).replace(/\./g, "");
export const fmtMoney = (v, currency, lang) => new Intl.NumberFormat(locale(lang), { style: "currency", currency: currency || "USD", maximumFractionDigits: 2 }).format(Number(v) || 0);

const NON_BILLABLE = new Set(["cancelled", "not_repairable", "abandoned"]);
export const isBillable = (o) => !NON_BILLABLE.has(String(o.status || "").toLowerCase());
export const orderTotal = (o) => (o.cost_estimate !== null && o.cost_estimate !== undefined && o.cost_estimate !== "" ? num(o.cost_estimate) : num(o.labor_cost));
export const orderSubtotal = (o, rate) => (rate > 0 ? orderTotal(o) / (1 + rate) : orderTotal(o));
export const companyName = (c) => (String(c?.company_name || "").trim() ? c.company_name : c?.name || "Cliente");

export function matches(order, company) {
  if (order.customer_id && company.id && order.customer_id === company.id) return true;
  const oc = String(order.customer_name || "").trim().toLowerCase();
  const cn = String(company.company_name || company.name || "").trim().toLowerCase();
  return !!cn && oc === cn;
}

export function serviceDescription(order) {
  const items = (Array.isArray(order.order_items) ? order.order_items : []).filter((i) => i && i.type !== "discount" && num(i.price) >= 0 && String(i.name || "").trim());
  if (items.length) return items.map((i) => (num(i.quantity) > 1 ? `${i.name} ×${Math.trunc(num(i.quantity))}` : i.name)).join(", ");
  return String(order.initial_problem || "").trim();
}

export const receivedDate = (o) => (o.created_date ? new Date(o.created_date) : null);
export function deliveredDate(o) {
  const hist = Array.isArray(o.status_history) ? o.status_history : [];
  let max = null;
  hist.forEach((e) => { if (e?.status === "delivered" && e.timestamp) { const t = new Date(e.timestamp); if (!Number.isNaN(t.getTime()) && (!max || t > max)) max = t; } });
  return max;
}

export function billingPeriod(orders) {
  const starts = orders.map(receivedDate).filter(Boolean);
  if (!starts.length) return null;
  const first = new Date(Math.min(...starts.map((d) => d.getTime())));
  const ends = orders.map((o) => deliveredDate(o) || receivedDate(o)).filter(Boolean);
  const last = ends.length ? new Date(Math.max(...ends.map((d) => d.getTime()))) : first;
  return { start: first, end: last };
}

const dayStr = (d) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;

async function fetchAllOrders(tenantId) {
  const out = [];
  for (let off = 0; off < 10000; off += 1000) {
    const { data, error } = await supabase.from("order").select("*").eq("tenant_id", tenantId).eq("is_deleted", false).order("created_at", { ascending: false }).range(off, off + 999);
    if (error) throw error;
    out.push(...(data || []));
    if (!data || data.length < 1000) break;
  }
  return out;
}

export async function loadCompanies(tenantId) {
  const [{ data: companies, error }, orders] = await Promise.all([
    supabase.from("customer").select("*").eq("tenant_id", tenantId).eq("is_b2b", true).limit(1000),
    fetchAllOrders(tenantId),
  ]);
  if (error) throw error;
  return (companies || []).filter((c) => orders.some((o) => matches(o, c) && isBillable(o) && orderTotal(o) > 0))
    .sort((a, b) => companyName(a).localeCompare(companyName(b), undefined, { sensitivity: "base" }));
}

export async function hasB2bCustomers(tenantId) {
  const { data } = await supabase.from("customer").select("id").eq("tenant_id", tenantId).eq("is_b2b", true).limit(1);
  return (data || []).length > 0;
}

export async function loadInvoiceableOrders(tenantId, company) {
  const [orders, invRes] = await Promise.all([
    fetchAllOrders(tenantId),
    supabase.from("invoice").select("order_ids").eq("tenant_id", tenantId).eq("customer_id", company.id).is("voided_at", null).limit(2000),
  ]);
  if (invRes.error) throw invRes.error;
  const done = new Set((invRes.data || []).flatMap((i) => (Array.isArray(i.order_ids) ? i.order_ids : [])));
  return orders.filter((o) => o.id && !done.has(o.id) && matches(o, company) && isBillable(o) && orderTotal(o) > 0);
}

export async function createInvoice({ tenantId, company, orders, subtotal, taxRate, taxAmount, total, currency, language, terms, dueDate, notes, createdBy, issuedAt }) {
  const period = billingPeriod(orders);
  const params = {
    p_tenant_id: tenantId, p_customer_id: company.id || null, p_customer_name: companyName(company), p_customer_tax_id: company.tax_id || null,
    p_order_ids: orders.map((o) => o.id), p_period_start: period ? dayStr(period.start) : null, p_period_end: period ? dayStr(period.end) : null,
    p_subtotal: subtotal, p_tax_rate: taxRate, p_tax_amount: taxAmount, p_total: total, p_currency: currency || "USD", p_language: language, p_payment_terms: terms,
    p_due_date: dueDate ? dayStr(dueDate) : null, p_notes: notes || null, p_created_by: createdBy || null, p_issued_at: issuedAt.toISOString(),
  };
  const { data, error } = await supabase.rpc("create_invoice", params);
  if (error) throw error;
  const row = Array.isArray(data) ? data[0] : data;
  if (!row) throw new Error("create_invoice no devolvió ninguna fila");
  return row;
}

export async function listInvoices(tenantId) {
  const { data, error } = await supabase.from("invoice").select("*").eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(200);
  if (error) throw error;
  return data || [];
}

export async function attachPDF(invoiceId, url) {
  const { error } = await supabase.from("invoice").update({ pdf_url: url }).eq("id", invoiceId);
  if (error) throw error;
}

export async function voidInvoice(invoiceId, reason) {
  const { error } = await supabase.from("invoice").update({ voided_at: new Date().toISOString(), void_reason: reason }).eq("id", invoiceId);
  if (error) throw error;
}

export async function uploadInvoicePDF(tenantId, invoiceNumber, blob, upsert = true) {
  const path = `tenants/${tenantId}/invoices/${invoiceNumber}.pdf`;
  const bucket = supabase.storage.from("uploads");
  const { error } = await bucket.upload(path, blob, { contentType: "application/pdf", upsert });
  if (error) throw error;
  return bucket.getPublicUrl(path).data.publicUrl;
}

async function logoDataUrl(url) {
  if (!url) return null;
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 5000);
  try {
    const res = await fetch(url, { mode: "cors", signal: ctrl.signal });
    if (!res.ok) return null;
    const blob = await res.blob();
    return await new Promise((resolve) => {
      const r = new FileReader();
      r.onload = () => {
        const img = new Image();
        img.onload = () => resolve({ dataUrl: r.result, w: img.naturalWidth, h: img.naturalHeight });
        img.onerror = () => resolve(null);
        img.src = r.result;
      };
      r.onerror = () => resolve(null);
      r.readAsDataURL(blob);
    });
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}

const BLUE = [46, 97, 242];
const WIN_ANSI_EXTRA = new Set([8364, 8218, 402, 8222, 8230, 8224, 8225, 710, 8240, 352, 8249, 338, 381, 8216, 8217, 8220, 8221, 8226, 8211, 8212, 732, 8482, 353, 8250, 339, 382, 376]);
const pdfSafe = (s) => {
  const base = String(s ?? "").replace(/→/g, "->").replace(/–/g, "-").replace(/—/g, "-").replace(/×/g, "x");
  let out = "";
  for (const ch of base) {
    const c = ch.codePointAt(0);
    if (c < 256 || WIN_ANSI_EXTRA.has(c)) { out += ch; continue; }
    const plain = ch.normalize("NFKD").replace(/[\u0300-\u036f]/g, "");
    out += /^[\x20-\xff]+$/.test(plain) ? plain : "?";
  }
  return out;
};

export async function buildInvoicePDF({ invoiceNumber, company, orders, subtotal, taxRate, taxAmount, total, notes, tenant, language, terms, issuedAt, dueDate, isVoided }) {
  const { jsPDF } = await import("jspdf");
  const lang = language === "en" ? "en" : "es";
  const s = (k) => pdfSafe(str(k, lang));
  const currency = tenant?.currency || "USD";
  const money = (v) => pdfSafe(fmtMoney(v, currency, lang));
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const W = 612;
  const H = 792;
  const L = 40;
  const R = W - 40;
  const logo = await logoDataUrl(tenant?.logo_url);
  const text = (t, x, y, { size = 10, style = "normal", color = [0, 0, 0], align, font = "helvetica" } = {}) => {
    doc.setFont(font, style);
    doc.setFontSize(size);
    doc.setTextColor(...color);
    doc.text(pdfSafe(t), x, y, { baseline: "top", align });
  };
  const truncate = (t, maxW, size, style = "normal") => {
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    let out = pdfSafe(t);
    if (doc.getTextWidth(out) <= maxW) return out;
    while (out.length > 1 && doc.getTextWidth(`${out}...`) > maxW) out = out.slice(0, -1);
    return `${out}...`;
  };
  const DARK = [85, 85, 85];
  let y = 40;
  if (logo) {
    const scale = Math.min(50 / Math.max(logo.h, 1), 170 / Math.max(logo.w, 1));
    try { doc.addImage(logo.dataUrl, "PNG", L, y, logo.w * scale, logo.h * scale); y += logo.h * scale + 8; } catch { y += 0; }
  }
  text(tenant?.admin_name || tenant?.name || s("workshopFallback"), L, y, { size: 22, style: "bold" });
  y += 26;
  [tenant?.address, tenant?.admin_phone && `${s("phone")}: ${tenant.admin_phone}`, tenant?.email].filter(Boolean).forEach((line) => { text(line, L, y, { size: 10, color: DARK }); y += 13; });
  const reg = String(tenant?.settings?.merchant_registration || "").trim();
  if (reg) { text(`${s("merchantReg")}: ${reg}`, L, y, { size: 10, color: DARK }); y += 13; }
  y += 4;
  doc.setDrawColor(190, 190, 190);
  doc.setLineWidth(0.6);
  doc.line(L, y, R, y);
  y += 12;
  text(s("invoice"), L, y, { size: 18, style: "bold", color: BLUE });
  text(invoiceNumber, R, y + 2, { size: 14, style: "bold", font: "courier", align: "right" });
  y += 24;
  text(`${s("issued")}: ${fmtDate(issuedAt, lang)}`, L, y, { size: 10, color: DARK });
  let ry = y;
  [`${s("terms")}: ${pdfSafe(termsLabel(terms, lang))}`, dueDate && `${s("due")}: ${fmtDate(dueDate, lang)}`].filter(Boolean).forEach((t) => { text(t, R, ry, { size: 10, style: "bold", color: DARK, align: "right" }); ry += 13; });
  y = Math.max(y + 14, ry) + 14;

  const totalW = W - 80;
  const billW = totalW * 0.62;
  const perW = totalW - billW - 12;
  const billLines = [[companyName(company), 13, "bold", [0, 0, 0]]];
  if (company.company_name && company.name && company.name !== companyName(company)) billLines.push([`${s("contact")}: ${company.name}`, 10.5, "normal", DARK]);
  const cp = [company.phone, company.email].filter(Boolean);
  if (cp.length) billLines.push([cp.join(" · "), 10.5, "normal", DARK]);
  if (String(company.tax_id || "").trim()) billLines.push([`${s("customerTaxId")}: ${String(company.tax_id).trim()}`, 10.5, "normal", DARK]);
  const perLines = [];
  const period = billingPeriod(orders);
  if (period) {
    const sameYear = period.start.getFullYear() === period.end.getFullYear();
    perLines.push([sameYear ? `${fmtShort(period.start, lang)} - ${fmtDate(period.end, lang)}` : `${fmtDate(period.start, lang)} - ${fmtDate(period.end, lang)}`, sameYear ? 13 : 11, "bold", [0, 0, 0]]);
  }
  perLines.push([devicesLabel(orders.length, lang), 10.5, "normal", DARK]);
  const boxH = Math.max(billLines.length * 15 + 26, perLines.length * 15 + 26);
  const box = (x, w, label, lines) => {
    doc.setFillColor(245, 245, 245);
    doc.setDrawColor(190, 190, 190);
    doc.setLineWidth(0.5);
    doc.roundedRect(x, y, w, boxH, 6, 6, "FD");
    let iy = y + 8;
    text(label, x + 12, iy, { size: 9, style: "bold", color: DARK });
    iy += 13;
    lines.forEach(([t, size, style, color]) => { text(truncate(t, w - 24, size, style), x + 12, iy, { size, style, color }); iy += 15; });
  };
  box(L, billW, s("billTo"), billLines);
  box(L + billW + 12, perW, s("period"), perLines);
  y += boxH + 14;

  const tableW = W - 80;
  const rowH = 34;
  const orderX = L + 8;
  const svcX = L + 62;
  const datesX = L + 340;
  const svcMax = datesX - svcX - 10;
  const amtR = L + tableW - 8;
  const headerRow = () => {
    doc.setFillColor(230, 230, 230);
    doc.roundedRect(L, y, tableW, 22, 4, 4, "F");
    const hy = y + 7;
    text(s("colOrder"), orderX, hy, { size: 8, style: "bold", color: DARK });
    text(s("colService"), svcX, hy, { size: 8, style: "bold", color: DARK });
    text(s("colDates"), datesX, hy, { size: 8, style: "bold", color: DARK });
    text(s("colAmount"), amtR, hy, { size: 8, style: "bold", color: DARK, align: "right" });
    y += 22;
  };
  const newPage = () => { doc.addPage(); y = 40; };
  headerRow();
  orders.forEach((o, i) => {
    if (y > H - 200) { newPage(); headerRow(); }
    if (i % 2 === 1) { doc.setFillColor(247, 247, 247); doc.rect(L, y, tableW, rowH, "F"); }
    const top = y + 6;
    const bottom = y + 19;
    text(truncate(o.order_number || o.id || "-", svcX - orderX - 6, 10, "bold"), orderX, top, { size: 10, style: "bold", font: "courier" });
    const device = [o.device_brand, o.device_family, o.device_model].filter(Boolean).join(" ").split(/\s+/).filter((w, idx, arr) => arr.findIndex((x) => x.toLowerCase() === w.toLowerCase()) === idx).join(" ") || "-";
    text(truncate(device, svcMax, 10, "bold"), svcX, top, { size: 10, style: "bold" });
    const desc = serviceDescription(o);
    if (desc) text(truncate(desc, svcMax, 8.5), svcX, bottom, { size: 8.5, color: [90, 90, 90] });
    const rec = receivedDate(o);
    const del = deliveredDate(o);
    text(truncate(`${rec ? fmtShort(rec, lang) : "-"} -> ${del ? fmtShort(del, lang) : "-"}`, 105, 8.5), datesX, top, { size: 8.5, color: [90, 90, 90] });
    text(money(orderSubtotal(o, taxRate)), amtR, top, { size: 10.5, style: "bold", align: "right" });
    y += rowH;
  });
  y += 14;
  if (y + 64 > H - 90) newPage();
  const labelX = R - 220;
  text(`${s("subtotal")}:`, labelX, y, { size: 10, color: DARK });
  text(money(subtotal), R, y, { size: 10, style: "bold", align: "right" });
  y += 16;
  const pct = Math.round(taxRate * 10000) % 10 === 0 ? (taxRate * 100).toFixed(1) : (taxRate * 100).toFixed(2);
  const taxLabel = String(tenant?.tax_label || "").trim() || "IVU";
  text(`${taxLabel} (${pct}%):`, labelX, y, { size: 10, color: DARK });
  text(money(taxAmount), R, y, { size: 10, style: "bold", align: "right" });
  y += 16;
  doc.setDrawColor(190, 190, 190);
  doc.setLineWidth(0.5);
  doc.line(labelX, y + 2, R, y + 2);
  y += 10;
  text(`${s("total")}:`, labelX, y, { size: 14, style: "bold", color: BLUE });
  text(money(total), R, y, { size: 14, style: "bold", color: BLUE, align: "right" });
  y += 22;
  const trimmed = String(notes || "").trim();
  if (trimmed) {
    y += 16;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(pdfSafe(trimmed), W - 80);
    const nh = lines.length * 12;
    if (y + nh + 12 > H - 90) newPage();
    text(s("notes"), L, y, { size: 9, style: "bold", color: DARK });
    doc.setTextColor(0, 0, 0);
    doc.text(lines, L, y + 12, { baseline: "top" });
  }
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p += 1) {
    doc.setPage(p);
    if (isVoided) {
      doc.saveGraphicsState();
      doc.setGState(new doc.GState({ opacity: 0.22 }));
      doc.setFont("helvetica", "bold");
      const fs = 92;
      doc.setFontSize(fs);
      doc.setTextColor(214, 48, 48);
      const word = s("voided");
      const half = doc.getTextWidth(word) / 2;
      const rad = (32 * Math.PI) / 180;
      const lift = 0.36 * fs;
      doc.text(word, W / 2 - half * Math.cos(rad) + lift * Math.sin(rad), H / 2 + half * Math.sin(rad) + lift * Math.cos(rad), { angle: 32 });
      doc.restoreGraphicsState();
    }
  }
  doc.setPage(pages);
  text(s("thanks"), W / 2, H - 60, { size: 11, style: "bold", color: BLUE, align: "center" });
  const now = new Intl.DateTimeFormat("sv-SE", { timeZone: "America/Puerto_Rico", dateStyle: "short", timeStyle: "short" }).format(new Date());
  text(`${s("generatedBy")} · ${now}`, W / 2, H - 30, { size: 8, color: [170, 170, 170], align: "center" });
  return doc.output("blob");
}

const esc = (t) => String(t ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");

export async function sendInvoiceEmail({ to, tenantId, invoiceNumber, company, orders, subtotal, taxRate, taxAmount, total, notes, tenant, language, terms, dueDate, pdfURL }) {
  const lang = language === "en" ? "en" : "es";
  const isES = lang === "es";
  const currency = tenant?.currency || "USD";
  const money = (v) => esc(fmtMoney(v, currency, lang));
  const fromName = tenantEmailFromName(tenant);
  const name = esc(companyName(company));
  const contact = esc(company.name || companyName(company));
  const rows = orders.map((o) => {
    const device = [o.device_brand, o.device_family, o.device_model].filter(Boolean).join(" ") || "—";
    const desc = serviceDescription(o);
    const rec = receivedDate(o);
    const del = deliveredDate(o);
    return `<tr><td style='padding:8px 6px;font-size:13px;color:#111;font-weight:600'>${esc(o.order_number || o.id || "-")}</td><td style='padding:8px 6px;font-size:13px;color:#555'>${esc(device)}${desc ? `<br><span style='color:#888;font-size:11px'>${esc(desc)}</span>` : ""}</td><td style='padding:8px 6px;font-size:11px;color:#888;white-space:nowrap'>${esc(rec ? fmtShort(rec, lang) : "—")} → ${esc(del ? fmtShort(del, lang) : "—")}</td><td style='padding:8px 6px;font-size:13px;color:#111;text-align:right;font-weight:600'>${money(orderSubtotal(o, num(taxRate)))}</td></tr>`;
  }).join("");
  const th = (t, right) => `<th style='padding:8px 6px;font-size:11px;color:#666;text-align:${right ? "right" : "left"};font-weight:600'>${esc(str(t, lang))}</th>`;
  const ordersBlock = `<div style='margin-top:18px'><div style='font-size:11px;font-weight:700;letter-spacing:0.4px;color:#666;margin-bottom:8px'>${isES ? "ÓRDENES INCLUIDAS" : "ORDERS INCLUDED"} (${orders.length})</div><table style='width:100%;border-collapse:collapse;border:1px solid #eee;border-radius:10px;overflow:hidden'><thead><tr style='background:#F8F9FA'>${th("colOrder")}${th("colService")}${th("colDates")}${th("colAmount", true)}</tr></thead><tbody>${rows}</tbody></table></div>`;
  const taxLabel = esc(String(tenant?.tax_label || "").trim() || "IVU");
  const totalsBlock = `<div style='margin-top:18px;padding:16px;background:#F8F9FA;border-radius:10px'><div style='font-size:11px;font-weight:700;letter-spacing:0.4px;color:#666;margin-bottom:8px'>${isES ? "TOTALES" : "TOTALS"}</div><table style='width:100%;border-collapse:collapse'><tr><td style='padding:6px 0;color:#666;font-size:13px'>${esc(str("subtotal", lang))}</td><td style='padding:6px 0;text-align:right;font-size:13px'>${money(subtotal)}</td></tr><tr><td style='padding:6px 0;color:#666;font-size:13px'>${taxLabel}</td><td style='padding:6px 0;text-align:right;font-size:13px'>${money(taxAmount)}</td></tr><tr style='border-top:1px solid #eee'><td style='padding:10px 0;font-size:14px;font-weight:700'>${esc(str("total", lang))}</td><td style='padding:10px 0;text-align:right;font-size:16px;font-weight:700;color:#2F61F2'>${money(total)}</td></tr></table></div>`;
  const tn = String(notes || "").trim();
  const notesBlock = tn ? `<div style='margin-top:18px;padding:14px;background:#FFF8E5;border-radius:10px;border-left:3px solid #F5A623'><div style='font-size:11px;font-weight:700;letter-spacing:0.4px;color:#A06A00;margin-bottom:6px'>${esc(str("notes", lang))}</div><div style='font-size:13px;color:#333;line-height:1.4'>${esc(tn)}</div></div>` : "";
  const tp = [`${str("terms", lang)}: ${termsLabel(terms, lang)}`];
  if (dueDate) tp.push(`${str("due", lang)}: ${fmtDate(dueDate, lang)}`);
  const termsBlock = `<div style='margin-bottom:16px;font-size:13px;color:#444'>${esc(tp.join(" · "))}</div>`;
  const pdfLink = pdfURL ? `<div style='margin-bottom:18px'><a href='${esc(pdfURL)}' style='display:inline-block;padding:10px 18px;background:#2F61F2;color:#fff;text-decoration:none;border-radius:8px;font-size:13px;font-weight:600'>${isES ? "Descargar factura (PDF)" : "Download invoice (PDF)"}</a></div>` : "";
  const line = (icon, v) => (v ? `<br><span style='color:#999;font-size:12px'>${icon} ${esc(v)}</span>` : "");
  const logoBlock = tenant?.logo_url ? `<div style='margin-bottom:14px'><img src='${esc(tenant.logo_url)}' alt='' style='max-height:48px;max-width:180px'></div>` : "";
  const html = `<!doctype html><html><body style='margin:0;padding:0;background:#F4F4F5;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;color:#111'><div style='max-width:640px;margin:0 auto;padding:24px'><div style='background:#fff;border-radius:14px;padding:28px 24px;box-shadow:0 1px 3px rgba(0,0,0,0.04)'>${logoBlock}<div style='font-size:18px;font-weight:700;color:#2F61F2;margin-bottom:6px'>${esc(fromName)}</div><div style='font-size:20px;font-weight:700;color:#111;margin-bottom:6px;line-height:1.3'>${isES ? "Factura" : "Invoice"} ${esc(invoiceNumber)}</div><div style='font-size:14px;color:#444;margin-bottom:6px;line-height:1.5'>${isES ? "Estimado/a" : "Dear"} ${contact} (${name}),</div><div style='font-size:14px;color:#444;margin-bottom:10px;line-height:1.5'>${isES ? "Aquí está el desglose de la factura consolidada de las órdenes de trabajo." : "Here is the breakdown of the consolidated invoice for the work orders below."}</div>${pdfLink}${termsBlock}${ordersBlock}${totalsBlock}${notesBlock}<div style='margin-top:28px;padding-top:18px;border-top:1px solid #eee;font-size:13px;color:#666;line-height:1.5'>${isES ? "Cualquier duda respondiendo este correo y te ayudamos." : "Reply to this email with any questions and we will help you."}${line("📞", tenant?.admin_phone)}${line("✉️", tenant?.email)}${line("📍", tenant?.address)}</div></div><div style='text-align:center;font-size:11px;color:#999;margin-top:14px'>${isES ? "Enviado por" : "Sent by"} ${esc(fromName)} · Powered by Archilla OS</div></div></body></html>`;
  return sendRawEmail({ tenantId: tenant?.id || tenantId, to, subject: `${isES ? "Factura" : "Invoice"} ${invoiceNumber} · ${companyName(company)}`, html, replyTo: tenant?.email, fromName });
}

export async function regenerateInvoicePDF({ invoice, tenant, isVoided: stamped }) {
  const ids = Array.isArray(invoice.order_ids) ? invoice.order_ids : [];
  if (!ids.length) throw new Error("La factura no tiene órdenes");
  const [ordersRes, custRes] = await Promise.all([
    supabase.from("order").select("*").in("id", ids),
    invoice.customer_id ? supabase.from("customer").select("*").eq("id", invoice.customer_id).limit(1) : Promise.resolve({ data: [], error: null }),
  ]);
  if (ordersRes.error) throw ordersRes.error;
  if (custRes.error) throw custRes.error;
  const rows = ordersRes.data || [];
  if (rows.length < ids.length) throw new Error("No se pudieron leer todas las órdenes de la factura");
  const company = custRes.data?.[0] || { name: invoice.customer_name || "Cliente", company_name: invoice.customer_name, tax_id: invoice.customer_tax_id };
  const order = new Map(rows.map((o) => [o.id, o]));
  return buildInvoicePDF({
    invoiceNumber: invoice.invoice_number, company, orders: ids.map((id) => order.get(id)).filter(Boolean), subtotal: num(invoice.subtotal), taxRate: num(invoice.tax_rate), taxAmount: num(invoice.tax_amount), total: num(invoice.total),
    notes: invoice.notes || "", tenant, language: invoice.language === "en" ? "en" : "es", terms: invoice.payment_terms || "due_on_receipt",
    issuedAt: invoice.created_at ? new Date(invoice.created_at) : new Date(), dueDate: invoice.due_date ? new Date(`${String(invoice.due_date).slice(0, 10)}T12:00:00`) : null, isVoided: stamped,
  });
}

export const regenerateVoidedPDF = ({ invoice, tenant }) => regenerateInvoicePDF({ invoice, tenant, isVoided: true });

export function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}

export function taxRateOf(tenant) {
  return normalizeTaxPercent(tenant?.settings?.tax_rate) / 100;
}

export const recipientEmail = (company) => {
  const billing = String(company?.billing_email || "").trim();
  if (billing) return billing;
  return String(company?.email || "").trim();
};

export const isVoided = (inv) => !!inv?.voided_at;
export function isOverdue(inv) {
  if (isVoided(inv) || !inv?.due_date) return false;
  const due = new Date(`${String(inv.due_date).slice(0, 10)}T00:00:00`);
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return due < today;
}
